name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: tests/bin
        retention-days: 1
  
  test:
    
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      # with:
        # Destination path
        # path:
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test --no-build --verbosity normal    
